# Generated by Django 3.1.3 on 2021-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da versão')),
                ('versao', models.CharField(max_length=15, verbose_name='Número da versão')),
                ('qtd_down', models.IntegerField(default=0, verbose_name='Quatidade de downloads')),
            ],
        ),
    ]
