# Generated by Django 3.1.3 on 2021-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='arq',
            field=models.CharField(default=-1, max_length=1500, verbose_name='Local do Arquivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versao',
            name='descricao',
            field=models.CharField(default=-1, max_length=1500, verbose_name='Descrição da versão'),
            preserve_default=False,
        ),
    ]
